### ISSUE TITLE
light sensor to detect when we cross lines on field?

### ISSUE THREAD

**Issue by clegoues** [GirlsOfSteelRobotics/2016GirlsOfSteel#14]
Should we do this?

**Comment by JosephJackson** [comment]
We evaluated this idea during the Tue, 1/26 meeting and concluded it's not worth trying. The carpet is dark green and the lines we care about are green gaffer's tape. The chances of us finding a reliable way to differentiate between the two aren't very good because there's not much contrast. Also, light sensing is always sensitive to the ambient lighting conditions at the field so we would need to cross our fingers and recalibrate at each competition.
